### ISSUE TITLE
Native Promises?

### ISSUE THREAD

**Issue by 58bits** [Opteo/oxen-queue#10]
Very nice.  Have you thought about swapping out bluebird for native promises?

**Comment by avermeil** [comment]
We certainly could! We'd need a small tweak to replace Bluebird's `Promise.timeout()`, but that's no big deal. Are you finding that bluebird is messing with your other code?

**Comment by 58bits** [comment]
Not messing with our other code at all. Just curious, as I believe the performance of native promises have improved in recent version of V8/Node.js, and I suppose that would be one less dependency. 

We re-implemented `addJObs` on our current stack - using Knex.js and our main application connection pool to submit jobs, and then Oxen to process the queue from its own host/instance. Again, very nice and just what we needed for the moment. 

Not at all related to Promises, but we need to be sure that our mail sending limited with AWS SES is respected, which is currently 14 messages per second. If I've done the math right, that's about 71ms per message. And so with your  fastest_polling_rate default which is 100ms - I believe we'll be fine. Does this sound right? (assuming a single instance of Oxen).

**Comment by avermeil** [comment]
For your SES rate limit, I don't think that the `fastest_polling_rate` is what you're looking for. `fastest_polling_rate` is designed to help you balance the throughput of the queue with the load on your mysql instance. But note that each "poll" can grab a batch of rows for the DB (where the batch size is correlated with the `concurrency` param). I suppose that you might be able to play with the `concurrency` and `fastest_polling_rate` params to make this lib behave like a throttler for your SES calls, but that's not what it was designed for.

Instead, I'd recommend taking a look at https://github.com/SGrondin/bottleneck, which we've been using rock-solid in production for years, both standalone and attached to a redis instance. Great library.

For your specific use-case, I'd recommend wapping your SES api calls with a Bottleneck throttler with a `minTime` of 72ms, and keeping Oxen as your job queue. That way you get to crank up your concurrency or queue length to whatever is convenient, while being sure that you'll never go above 14 messages per second. IMO, those are independent concerns.

If your queue really is exclusively for managing SES call throttling, you could even consider using Bottleneck only :)

**Comment by 58bits** [comment]
@avermeil - wow - thanks a bunch for the reply. Very much appreciated. I've taken a quick look at Bottleneck and this looks great. Thanks for pointing us in the right direction. Also thanks for clarifying `fastest_polling_rate ` and `concurrency `.  

We really like the priority feature of Oxen as well. We have two queues - one for system emails and mailshots, and one for onboarding which must take priority.

Our system email Oxen queue is configured as...

```
/**
 * Define and start the system email processing queue
 */
const JOB_TYPE_SYSTEM = 'system_emails'
const JOB_DB = 'oxen_queue'
const systemEmails = new Oxen({
  mysql_config: config.db,
  db_table: JOB_DB,
  job_type: JOB_TYPE_SYSTEM,
})

const startSystemEmailQueue = async () => {
  systemEmails.process({
    work_fn : async function (payload) {
      logger.info({ queue: JOB_TYPE_SYSTEM, payload })
      return processEmail(payload) // Returns a promise with resolved or rejected
    },
    concurrency : 5,
  })
}
```

So with Bottleneck, we could wrap `processEmail` in...

```
const wrapped = limiter.wrap(processEmail)
```

and then inside the queue replace ` return processEmail(payload)` with...

```
return wrapped(payload) 
```

Look okay?

Again, thanks a bunch for the replies. 

Since at this point this has little to do with native promises in Oxen, I'll go ahead and close the issue. ;-)

Best,

Tony

**Comment by avermeil** [comment]
Yep, you've got it right :)

One additional optimisation, assuming that you've got other async calls besides your SES API call in `processEmail`, could be to throttle only the SES call:

```
/**
 * Define and start the system email processing queue
 */
const JOB_TYPE_SYSTEM = 'system_emails'
const JOB_DB = 'oxen_queue'
const systemEmails = new Oxen({
    mysql_config: config.db,
    db_table: JOB_DB,
    job_type: JOB_TYPE_SYSTEM,
})

const startSystemEmailQueue = async () => {
    systemEmails.process({
        work_fn: async function (payload) {
            logger.info({ queue: JOB_TYPE_SYSTEM, payload })
            return processEmail(payload) // Returns a promise with resolved or rejected
        },
        concurrency: 5,
    })
}

const processEmail = async ({ user_id }) => { // assuming payload contains user_id ¯\_(ツ)_/¯
    const email_template = await readTemplateFromDisk()
    const user_info = await getUserInfo(user_id)
    const final_html_content = compileTemplate(email_template, user_info)

    return sendEmail({ email: user_info.email, html: final_html_content })
}

// By throttling only the specific rate-limited call, you squeeze out a bit more throughput, 
// and incidentally you'll still be rate-limit safe if, as your code evolves, you need to call sendEmail directly (outside of a queue)
const sendEmail = args => wrapped(aws_lib.sendSESEmail(args))

```

But maybe you're doing this already!

Anyway, happy coding ❤️

**Comment by 58bits** [comment]
As a side note, Nodemailer via the SES transport has an SES rate-limiting feature. That said, Oxen and Bottleneck are still ideal for our use case, and we now also have a solution/option for switching to the native AWS.Ses api should we wish to in the future. Thanks again. T.
