### ISSUE TITLE
Cancelled State?

### ISSUE THREAD

**Issue by 58bits** [Opteo/oxen-queue#11]
I think we may have a use case for a 'cancelled' state, although not 100% sure yet. 

We'd like the option to stop processing jobs that are part of a large(ish) mail queue. 

We could in theory mark them as failed, or even stuck (if we start `ox.process` with `recover_stuck_jobs = false`) but this doesn't seem like the intended use for these states.

In our scenario, we'd have an 'emergency cord' that we could pull by marking all of the remaining 'waiting' jobs for a particular queue, or job type with 'cancelled' (without having to shutdown the queue).

Thoughts?  

If this makes sense, would you be interested in a PR?

**Comment by 58bits** [comment]
Ah - if we've understood https://github.com/Opteo/oxen-queue/blob/0ae2a35f8863f12c510e1711a78c3bfe32e47e5e/lib/queue.js#L245 - then the queue will ignore any job that has a status other than 'waiting', 'processing', 'stuck' - and so simply inserting / updating with our own 'cancelled' status code should 'just work'.

**Comment by avermeil** [comment]
I think that should work, yes. Or you could mark them as "error", "success", or even delete the rows. 

I feel a bit weird about recommending that you do mutations directly on the DB like that (as opposed to writing purpose-built functions in the lib), but then again that's kind of the benefit of using an SQL table for queuing! It's simple enough that you can operate on it directly with little risk of ending up in a bad state.

**Comment by 58bits** [comment]
Understood, and thanks again ;-)
